# Code taken from: https://vercel.com/guides/how-can-i-use-github-actions-with-vercel

name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy to Vercel
        id: deploy
        run: |
          echo 'VERCEL_DEPLOY<<EOF'
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
          echo EOF
          >> $GITHUB_OUTPUT

      - name: Parse vercel domain
        id: domain-parse
        run: echo ${{ join(steps.deploy.outputs.*, '/n') }} | grep -m 1 -o '[^.]\+\.vercel\.app' >> $GITHUB_OUTPUT
      - name: Assign Branch preview domain
        run: |
            ALIAS="${{github.ref_name}}.dev.revohacks.com
            NEW_DEPLOYMENT_URL=$(echo ${{ steps.domain-parse.outputs.VERCEL_DEPLOY }})

            # Check if the alias exists
            echo "Checking if the alias '$ALIAS' exists..."
            EXISTING_ALIAS=$(vercel alias ls --json | jq -r --arg ALIAS "$ALIAS" '.aliases[] | select(.alias == $ALIAS) | .alias')

            if [ "$EXISTING_ALIAS" == "$ALIAS" ]; then
              echo "Alias '$ALIAS' exists. Deleting it..."
              vercel alias rm "$ALIAS" -y --token=${{ secrets.VERCEL_TOKEN }}
              if [ $? -eq 0 ]; then
                echo "Alias '$ALIAS' deleted successfully."
              else
                echo "Failed to delete alias '$ALIAS'."
                exit 1
              fi
            else
              echo "Alias '$ALIAS' does not exist. No need to delete."
            fi
            vercel alias set "$NEW_DEPLOYMENT_URL" "$ALIAS" --token=${{ secrets.VERCEL_TOKEN }}